spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  security:
    token:
      signingKey: bd71cbe90156c76422679fab3b4ca369177e6884e963cbcb3263df3b6169bcf7

server:
  port: 8080

logging:
  level:
    root: info